# Site settings
title: Lorem Ipsum - Web Developer
description: "ZhaoQingLong's Blog ..."
baseurl: "/blog" # for test: remove string '/space-jekyll-template' to ''
url: "https://quiqijingfeng.github.io/blog/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: ZhaoQingLong
user_title: ZhaoQingLong
#Emal地址
email: gejinnian224@outlook.com
#twiter账号
twitter_username: QueQiJingFeng
#github账号
github_username:  QuiQiJingFeng
#google+账号
gplus_username:  QuiQiJingFeng
#领英
linkedin_public_url: QuiQiJingFeng # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: QuiQiJingFeng
profile_picture: http://www.pptbz.com/pptpic/UploadFiles_6909/201203/2012031220134655.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: 主页
      url: /
      key_trigger: 1
    - title: 博客
      url: /posts
      key_trigger: 2
    - title: 分类
      url: /series
      key_trigger: 3
    - title: 标记
      url: /tags
      key_trigger: 4
    - title: 关于
      url: /about
      key_trigger: 5
  # section_2:
  #   - title: github
  #     url: http://www.github.com/QuiQiJingFeng
  #     new_tab: true
  #     key_trigger: g
  #   - title: twitter
  #     url: http://www.twitter.com/QueQiJingFeng
  #     key_trigger: t
  #   - title: search
  #     url: ""
  #     key_trigger: s #WARNING: search only works with "s"

# projects in header index
# projects:
#   - name: M2_SERVER
#     url: https://github.com/QuiQiJingFeng/M2_SERVER
#   - name: M2_CLIENT
#     url: https://github.com/QuiQiJingFeng/M2_CLIENT
#   - name: WECHAT_GAME
#     url: https://github.com/QuiQiJingFeng/laya_slgc

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
